mod display_file;
mod character_set;
mod renderer;

// ZX81 Video system
// Character-based display: 32×24 text
// Display generated by CPU in SLOW mode
pub struct Video {
    // TODO: Add display buffer
}

impl Video {
    pub fn new() -> Self {
        Self {}
    }

    pub fn render_frame(&mut self) {
        // TODO: Render a frame from display file
    }
}
